### ISSUE TITLE
Does not work with nova 4

### ISSUE THREAD

**Issue by atymic** [slovenianGooner/nova-searchable-select#34]
Get the following error in the JS console. Field does not show at all.

Repo looks pretty dead, if you're accepting PRs I will attempt to debug and fix :)

```
runtime-core.esm-bundler.js:226 TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.render (searchable-select:formatted:16179:29)
    at Fn (runtime-core.esm-bundler.js:888:44)
    at we.fn (runtime-core.esm-bundler.js:5600:57)
    at we.run (reactivity.esm-bundler.js:185:25)
    at R.e.update (runtime-core.esm-bundler.js:5714:56)
    at R (runtime-core.esm-bundler.js:5728:9)
    at j (runtime-core.esm-bundler.js:5510:9)
    at N (runtime-core.esm-bundler.js:5468:17)
    at g (runtime-core.esm-bundler.js:5058:21)
    at E (runtime-core.esm-bundler.js:5254:13)
```

**Comment by faraizihove** [comment]
did yo come right with this package in Nova 4?

**Comment by weeger** [comment]
Same here !

**Comment by arturasfrontit** [comment]
Tried use in searchable select:

ypeError: e._self is undefined
    render searchable-select:1
    qn runtime-core.esm-bundler.js:914
    effect runtime-core.esm-bundler.js:5649
    run reactivity.esm-bundler.js:190
    update runtime-core.esm-bundler.js:5763

**Comment by guillermo-lopez** [comment]
any solutions?

**Comment by weeger** [comment]
I think my solution was just to get rid of this plugin and replace it with the integrated tools of Nova 4.
